### ISSUE TITLE
是否可使用 XRDP、VNC 進行遠端監看畫面？

### ISSUE THREAD

**Issue by p33994451** [andrewintw/rpi-video-sync-looper#2]
您好，首先感謝您們各位和社群的同伴共同協力開發此項計畫！

作為樹莓派初學者，剛已初步覺得測試成功；目前使用一台子機外接螢幕（3B+），另一台4B作為主機，透過SSH進行重開機指令的測試；先讓子機播放影片一陣子後再開主機運作後，子機確實會同步回到主機剛開始播放的秒數。

只是因之前是使用 XRDP 或 VNC 來進行無鍵盤、滑鼠監看樹莓派的操作，所以才會有此疑問；剛有嘗試使用 XRDP 和 VNC 連主機，但VNC有提示無法顯示桌面；XRDP則是只會呈現一行純文字介面。

如果確定因為系統穩定而無法也沒關係，再次感謝您們的發想與開發！

**Comment by andrewintw** [comment]
Hi @p33994451 

目前系統沒有這樣的功能。因為我所使用的 base linux 是 lite 版本的 Raspbian，不支援 x-window。

我印象中 omxplayer 顯示的對象是 framebuffer（這也是為何它不需要 x-window 的原因）。所以我不確定 XRDP/VNC 是否能顯示 omxplayer 的播放畫面。

但是我可以提供一個驗證方向：

1. 下載帶有 x-window 的 image 並燒錄至 SD 卡開機: 
   * http://ftp.jaist.ac.jp/pub/raspberrypi/raspios_full_armhf/images/raspios_full_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-full.zip
2. 安裝並設定 XRDP/VNC，XRDP/VNC 可以運作。
3. 透過文件中的 [方法二：於現有的 Raspbian 環境中安裝 RPi-Video-Sync-Looper 套件](https://github.com/andrewintw/rpi-video-sync-looper/blob/main/README.zh_TW.md#%E6%96%B9%E6%B3%95%E4%BA%8C%E6%96%BC%E7%8F%BE%E6%9C%89%E7%9A%84-raspbian-%E7%92%B0%E5%A2%83%E4%B8%AD%E5%AE%89%E8%A3%9D-rpi-video-sync-looper-%E5%A5%97%E4%BB%B6)
5. 使 RPi-Video-Sync-Looper 運作起來，並嘗試使用 XRDP/VNC 連線試試看。

希望對你有所幫助。如果有測試結果的話，也希望能回報一下。

感謝

**Comment by p33994451** [comment]
收到！感謝您分享的驗證方向！我會再來測試看看並回報結果！

**Comment by andrewintw** [comment]
沒有 next action, 暫時關閉
