### ISSUE TITLE
'slave' not playing - Solution: mandatory length of video

### ISSUE THREAD

**Issue by LauraLivers** [andrewintw/rpi-video-sync-looper#5]
FYI: If any file is less than 60 seconds long, the syncs won't.
the 'slave' rpi will get stuck at the start screen (logged into the rpi, but no video playing). 
Found the error by checking out the original omxplayer-sync page here: https://github.com/turingmachine/omxplayer-sync
maybe add its usage notes to your page as well?
otherwise works wonderfully! Thank you so much

**Comment by andrewintw** [comment]
> FYI: If any file is less than 60 seconds long, the syncs won't.
> the 'slave' rpi will get stuck at the start screen (logged into the rpi, but no video playing).
> Found the error by checking out the original omxplayer-sync page here: https://github.com/turingmachine/omxplayer-sync
> maybe add its usage notes to your page as well?
> otherwise works wonderfully! Thank you so much

Thank you very much for providing this information.
I will update the documentation to include this limitation description. <3
